# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Bite',
    'version': '1.1',
    'summary': 'Bite',
    'sequence': 15,
    'description': 'Bite',
    'category': 'New',
    'website': 'https://www.odoo.com/page/billing',
    'images': [],
    'depends': ['base', 'web', 'mail'],
    'data': [
        'data/bite.xml',
        'security/bite_security.xml',
        'security/ir.model.access.csv',
        'views/menu_view.xml',
        'views/crawl_book_view.xml',
        'views/editor_view.xml',
        'views/article_view.xml',
        'views/series_view.xml',
        'views/category_view.xml',
        'views/category_pins_view.xml',
        'views/tags_view.xml',
        'views/tag_pins_view.xml',
        'views/photo_view.xml',
        'views/site_view.xml',
        'views/blog_domain_view.xml',
        'views/language_view.xml',
        'views/tag_analysis_view.xml',
        'wizard_views/cron_service_view.xml',
        'wizard_views/transfer_service_view.xml',
        'wizard_views/photo_service_view.xml',
        'wizard_views/export_service_view.xml'
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}